### ISSUE TITLE
packin sunsui

### ISSUE THREAD

**Issue by hieplq** [hieplq/motive#7]
16:42:54.577===========> DB.executeUpdate: INSERT INTO t_alter_column values('S_Resource','AD_User_ID','NUMERIC(10)','NOT NULL',null) [SvrProcess_615b0777-ae70-4006-a9ba-b584aa8da73c] [259]
org.postgresql.util.PSQLException: ERROR: column "ad_user_id" of relation "s_resource" contains null values
  Where: SQL statement "alter table s_resource alter column ad_user_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 116 at EXECUTE; State=23502; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:134)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502)
	at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:130)
	at com.sun.proxy.$Proxy15.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1045)
	at org.compiere.util.DB.executeUpdate(DB.java:944)
	at org.compiere.util.DB.executeUpdate(DB.java:930)
	at org.adempiere.pipo2.handler.ColumnElementHandler.createColumn(ColumnElementHandler.java:298)
	at org.adempiere.pipo2.handler.ColumnElementHandler.syncColumn(ColumnElementHandler.java:201)
	at org.adempiere.pipo2.handler.ColumnElementHandler.startElement(ColumnElementHandler.java:178)
	at org.adempiere.pipo2.PackInHandler.processElement(PackInHandler.java:237)
	at org.adempiere.pipo2.PackInHandler.processElement(PackInHandler.java:253)

**Comment by hieplq** [comment]
ERROR: insert or update on table "ad_element" violates foreign key constraint "entityt_adelement" Detail: Key (entitytype)=(QSS_LCO) is not present in table "ad_entitytype".

reason:
has item of sunsui on Withholding Category

**Comment by hieplq** [comment]
table TH_SS_PD_Report_Detail_Pb reference to inactive window
